### ISSUE TITLE
Plans for geoxarray?

### ISSUE THREAD

**Issue by rsignell-usgs** [geoxarray/geoxarray#1]
@djhoese , would be interested in discussing your plans for geoxarray with some folks in the Earth System Information Partners (ESIP) community?  

I'm thinking of a "Tech Dive" discussion:
http://wiki.esipfed.org/index.php/Interoperability_and_Technology/Tech_Dive_Webinar_Series

 Feel free to contact me offline at `<removed email>`

**Comment by djhoese** [comment]
@rsignell-usgs FYI I removed your email from the above post. I figured you didn't want more spam in your inbox.
